#!/usr/bin/env bash

build_path="build/scripts"
COLUMNS=12
PS3='Please enter your choice: '
options=(
        "Build all: manifest, functions file, and KES script"
        "Build manifest only"
        "Build functions file only"
        "Build KES script only"
        "Build local: build all files and load from local server"
        "Quit"
)
declare -A scripts
scripts["LOCAL"]="local.sh"
scripts["FUNCS"]="concat_funcs"
scripts["MANIFEST"]="gen_manifest.sh"
scripts["KES"]="gen_kes.sh"

set_branch(){
    select opt in main testing; do
        branch=$opt
        break
    done
    echo "$branch"
}

build(){
    local branch=""
    echo "${scripts[$1]}"
exit
    case "$1" in
        Build[[:space:]]all*)
            branch=$(set_branch)
            for i in "FUNCS" "MANIFEST" "KES"; do
                ${build_path}/${scripts[$i]} "$branch"
            done
            ;;
        Build[[:space:]]manifest*)
            ${build_path}/${scripts["MANIFEST"]}
            ;;
        Build[[:space:]]functions*)
            ${build_path}/${scripts["FUNCS"]}
            ;;
        Build[[:space:]]KES*)
            branch=$(set_branch)
            ${build_path}/${scripts["KES"]} "$branch"
            ;;
        Build[[:space:]]local*)
            ${build_path}/${scripts["LOCAL"]}
            ;;
    esac
}
abort(){
    printf "Invalid option or outside of range\n"
    exit 1
}
validate(){
    [[ $1 -eq 0 ]] && return 0
    [[ $1 -lt 0 ]] && abort
    [[ $1 -gt ${#scripts[@]} ]] && abort
}

select opt in "${options[@]}"; do
    [[ $opt == "Quit" ]] && exit 0
    ind=$(($REPLY-1))
    validate "$ind"
    build "$opt"
    break
done
