#!/usr/bin/env bash
TEST_NAME="Dangling newline in mod scripts"
if [[ ! $(git rev-parse --show-toplevel 2>/dev/null) == "$PWD" ]]; then
    echo "Must be run from repository root"
    exit 1
fi

abort(){
    local file="$1"
    printf "File '%s' does not end in '}'\n" "$file"
    exit 1
}

readarray -t files < <(find $PWD/mods -mindepth 1 -type f -name "*.js")
for file in "${files[@]}"; do
    [[ $(tail -n1 "$file") != "}" ]] && abort "$file"
done
exit 0
