#!/usr/bin/env bash
TEST_NAME="Check for missing mod functions"
find_mods(){
    readarray -t mods < <(find mods/ -mindepth 1 -type d | sort)
    for mod in "${mods[@]}"; do
        basename "${mod}"
    done
}
find_funcs(){
    grep "//mes-func" helpers/funcs.js | awk -F: '{print $1}' | sed 's/ //g' | sort
}
abort(){
    local msg="$1"
    local res="$2"
    printf "%s\n" "$msg"
    printf "%s\n" "$res"
    exit 1
}

if [[ ! $(git rev-parse --show-toplevel 2>/dev/null) == "$PWD" ]]; then
    echo "Must be run from repository root"
    exit 1
fi

branch=$(git name-rev --name-only HEAD)

if [[ ! $branch == "testing" ]] && [[ ! $branch =~ release/ ]]; then
    exit 0
fi

res=$(comm -23 <(find_mods) <(find_funcs))
if [[ ! $res == "" ]]; then
    abort "Found local mods not present in funcs.js:" "$res"
fi

res=$(comm -13 <(find_mods) <(find_funcs))
if [[ ! $res == "" ]]; then
    abort "Found functions in funcs.js not present as local mods:" "$res"
fi

exit 0
