name: Bug report test
description: Submit bugs that affect functionality here
title: "[BUG] Your title here"
labels: ["bug"]
assignees:
  - aclist
body:
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Firefox-based
        - Chromium-based
        - Safari
        - Other (respond in comments)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: handler
    attributes:
      label: Script manager
      options:
        - Greasemonkey
        - Tampermonkey
        - Violentmonkey
        - Other (respond in comments)
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: KES version
    validations:
      required: true
      placeholder: "E.g., 4.2.0"
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: What did you expect to happen?
      placeholder: "E.g., When doing X, Y occurred. Include as much detail as possible."
    validations:
      required: true
