name: Feature request
description: Suggest a feature for the KES interface
title: "[FEAT] Your title here"
labels: ["enhancement"]
assignees:
  - aclist,pamasich
body:
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Firefox-based
        - Chromium-based
        - Safari
        - Other (respond in comments)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: handler
    attributes:
      label: Script manager
      options:
        - Greasemonkey
        - Tampermonkey
        - Violentmonkey
        - Other (respond in comments)
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: KES version
    validations:
      required: true
      placeholder: "E.g., 4.2.0"
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the feature
      description: What kind of functionality, and why? Who will this benefit?
      placeholder: "E.g., Add a feature to the X area that supports doing Y. Currently, it's not possible to do Y because of Z. Adding X will help with scenarios A, B, and C. Include as much detail as possible."
    validations:
      required: true
