name: test-workflow

on:
  pull_request_target:
      types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.head_ref, 'fix')
      && !startsWith(github.head_ref, 'feat')
    
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Invalid branch name."
