:nofooter:
:toc: left
:stylesheet: custom.css
:icons: font

= kbin Enhancement Suite (KES)
Add-on manager for kbin enhancement scripts | Last updated: {d}

Click https://aclist.github.io/kes/kes_dark.html[here] for dark mode

== Description

kbin Enhancement Suite (KES) bundles together many userscripts that add various features to kbin and adds an integrated interface for configuring them.

As such, KES is three things:

- A curated and audited collection of modifications (userscripts)
- A menu for managing this collection of modifications
- A framework for authors to add new modifications

For users, it provides a "single pane of glass" from which to manage various usability/customization options.

For script authors, it provides a simple, human-readable format to integrate new options with minimal overhead and describes a
standardized framework for sharing settings between scripts.

[NOTE]
Modifications are variously referred to as "features," "add-ons," and "mods" within this document.

== Prerequisites

KES is itself a userscript that bundles other scripts. It requires any of the below
browser extensions in the *monkey family to run:

- https://www.tampermonkey.net/[TamperMonkey]
- https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/[GreaseMonkey] (Firefox only)
- https://violentmonkey.github.io/[ViolentMonkey]

Versions for Firefox- and Chromium-based browsers can be found on your respective add-on/extensions page.

== Installation

Navigate to https://github.com/aclist/kbin-megamod/raw/main/megamod.user.js[the install script] and
follow your browser extension's onscreen prompts to install it. Subsequent updates should be handled
seamlessly, and KES will notify you if there is a new version available.

== Usage

=== Main menu
To open the KES settings menu, press `Ctrl-Shift-L` or click the wrench icon in the top right corner of the page.
Pressing `Ctrl-Shift-L` again, or clicking on the close button or anywhere outside of the menu will close it.

The menu is divided into pages; each page contains a list of modifications.
You can switch between pages by clicking on the page name in the list on the left side of the menu (or the top if on mobile).

Clicking the name of a modification will open an information panel with a description of the modification and a toggle to enable/disable it.
If the modification has any additional settings, they can be configured here.

On devices where the menu doesn't take up the whole screen, it can be docked to the bottom of the screen by clicking the arrow
icon in the top right corner of the menu. Clicking the arrow again will undock the menu.

=== Settings
The toggle state of a modification and its settings will be saved and persist across browser sessions.

To submit a bug report/feature request or visit the KES home page, follow the links shown within the KES menu itself.

== Developers

=== Basic workflow
If you wish to submit your scripts for integration into KES, a standardized framework is available that
makes adaptation and PR submission easy:

The metadata related to a script is defined a priori in the file `manifest.json`. KES automatically populates
its pages and assigns your add-on to the category requested, filling its contents with the fields and values you set.

1. Set up an entrypoint function in the script which enables/disables it (See <<Script calling logic>>)
2. Receive a boolean toggle argument from KES passed to the above function indicating
whether the user has toggled the script on or off
3. If the script defines custom input fields, use the `getModSettings()` function exposed by KES
with your script's namespace as the argument (See <<Retrieving custom settings>>)
4. Parse the resulting settings object for your desired keys and use these settings in the business
logic of your script

Detailed explanations follow.

=== JSON manifest

`manifest.json` consists of an array of objects that each represent an add-on, that is, an atomic
feature provided by a function in a third-party userscript.
Add-ons must be given a globally unique entrypoint function name and, if using custom input fields,
a globally unique namespace.

If the add-on requires custom input fields like select, radio, or
other https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input[input types], they can be added under
the `fields` array, one custom field per object.

The namespace is used to store settings under a localStorage object, which is used to share
settings between KES and third-party add-ons, or between third-party add-ons.


.localStorage
----
Storage {
    "kes-settings": <1>
        '{
            "addMail":true,
            "initMags":true,
            "magInstanceEntry":true,
            "hideDownvotes":true,
            "hideUpvotes":true,
            "updateTime":true,
            "changeLogo":false,
            "dock":"up",
            "checksInit":true
        }',
    codehighlights: '{"style":"gruvbox"}', <2>
    languagefilter: '{"filter":"English"}',
    mail: '{"type":"Text","text":"PM","state":"on"}',
    timestamp: '{"offset":"Local time","state":"on"}',
    length: 6
}
----

<1> In the above example, KES has saved the state of eight add-ons, seven of which are enabled by the user.
In addition, it has stored the position of the KES window to `up`. (This is not controlled by third party add-ons.)
<2> Finally, the four add-ons `codehighlights`, `languagefilter`, `mail`, and `timestamp` have respectively saved
their own settings in custom namespaces. (The other three add-ons did not request any custom settings fields.)

KES handles toggling of add-ons and passes their boolean state to the recipient script on pageload events and changes to the thread/post content area.

The recipient script therefore does not need to poll this state or watch for page changes, as it is called as an internal function of KES when needed.

The only responsibilities of the recipient script are:

- Handle setup and teardown of the desired logic (show/hide elements, apply/unapply styling)
- Parse its own namespace under localStorage and retrieve custom settings. To facilitate this, KES provides the `getModSettings()` function. See <<Retrieving custom settings>>.

.manifest.json
----
  {
    "name": "Add mail",
    "author": "shazbot",
    "version": "0.1.0",
    "label": "Add mail icon",
    "desc": "Add mail link to usernames if on kbin.social",
    "login": false,
    "recurs": true, <1>
    "link": "mypage.dotcom",
    "link_label" "My link"
    "entrypoint": "addMail",
    "namespace": "mail", <2>
    "fields": [ <3>
      {
        "type": "radio",
        "initial": "Text",
        "key": "type",
        "label": "Label type",
	"values": [
		"Text",
		"Icon"
	]
      },
      { <4>
        "type": "text",
        "initial": "PM",
        "key": "text",
        "label": "Link label"
      }
    ],
    "page": "general" <5>
  }
----
<1> If the user has enabled lazy loading (infinite scroll) and the add-on modifies new threads and/or comments, setting this value to true will ensure that the script is applied again.
<2> A globally unique namespace under which the script's custom field settings are stored.
<3> See <<Adding custom input fields>>. In the above example, the descriptive text 'Label type' will be printed on one line, followed by a line break, then two radio buttons respectively labeled 'Text' and 'Icon', in that order,
separated by line breaks, with the 'Text' radio button initially selected. The value 'Text' will be saved under the `mail.type` key (i.e., prefer a text label instead of icon) and updated if the user changes the radio button.
<4> This is followed by a descriptive label reading 'Link label', a line break,
and then a textarea initially set to the string 'PM', with this value stored under the `mail.text` key. In this example, the link label would be used by the recipient script if `mail.type` was set to `Text`. KES is agnostic to how these settings are parsed and merely populates the fields.
As far as KES is concerned, functionality of one field does not depend on another; it is up to the author to add additional fields if necessary.
<5> The contents of the metadata and custom fields will be added to the 'General' page of the sidebar under the feature label 'Add mail icon'. Available pages can be seen within the file `ui.json`.

.basic metadata
[%autowidth]
|===
|Key|Optional?|Type|Value

|name||string|An internal, "official" name of the add-on, possibly more verbose than the user-facing string
|author||string|The author of the add-on. This is user-facing and links back to the named profile on kbin. If you are on an instance other than kbin.social, include the full @<user>@<instance> designation here
|version||string|An internal version number
|label||string|A short, descriptive name of the feature, used when printing it in the list of options. This
functions as the "name" of the feature seen by users
|desc||string|A human-readable description of what the feature does
|login||boolean|Whether the option requires being logged into the site to function/display correctly
|recurs||boolean|If the feature should recur and apply to new elements in the tree in the event of DOM changes
to the `'#content'` area, such as new posts or threads when lazy load (infinite scrolling) is enabled
|entrypoint||string|A globally unique function entrypoint in the recipient script used to toggle the feature
on or off.
|namespace|yes|string|A globally unique namespace used if the add-on exposes custom input fields (see below)
This namespace is used when parsing localStorage
|link|yes|string|A link to external content, such as a web site or help file
|link_label|yes|string|A human-readable label for the link above
|fields|yes|string|An array of objects containing custom input fields
|===

=== Adding custom input fields

.The fields array
[%autowidth]
|===
|Key|Optional?|Type|Value

|type||string|The input field type
|initial||string (if checkbox, bool)|The initial value the field is set to
|key||string|A unique key for this setting, stored under the object namespace defined in Table 1
|label|yes|string|A descriptive label of what the setting does, printed above the input field
|values|required if `type` is select or radio|array of strings|If the type is `select` or `radio`, an array of human-readable labels, which also function as values, used to populate each option
|checkbox_label|required if `type` is checkbox|string|A human-readable label printed to the right of a checkbox
|===

=== Script calling logic
A number of pre-existing examples can be found under the `/mods` directory of the repository.

KES calls the recipient script via the entrypoint function defined in `manifest.json` with a boolen argument.
----
function toggleOn(){
   let el = document.querySelector('.myelement')
   if (!el) {
       document.body.appendChild(el);
   }
}
function toggleOff(){
   $('.myelement').hide();
}
function myEntryPoint(toggle) {
    if (toggle)
        toggleOn();
    } else {
        toggleOff();
}
----

Bear in mind that if you have defined custom input fields, such as choosing between different label/icon types or supporting custom strings, or
when an infinite scroll event occurs (<<Handling infinite scrolling>>), KES may attempt to call the entrypoint function again and apply the new settings.

Therefore, if the element being modified already exists, you should add logic to either override its current value or return gracefully, as seen in the boilerplate example above.
Otherwise, the same element may be created multiple times.

=== Retrieving custom settings

Parsing your script's setting is as simple as calling `getModSettings()` with the desired namespace and applying those accordingly.

You can also leverage this function to retrieve the settings of other scripts for more synergistic functionality.

----
const myNs = "mymod";
const settings = getModSettings(myNs);
const color = settings["color"];
const mydiv = document.querySelector("mydiv");
mydiv.style.cssText = "background-color:" + color;
----

Taking the example function from an earlier section, we can combine it with the above to ensure
that if the element does not exist, it is created, and if it does exist, it is updated with the
latest setting the user applied. With this basic flow, a user can change colors/labels/other parameters
within the KES menu and see them updated immediately.

----
function toggleOn(){
   let el = document.querySelector('.myelement')
   if (!el) {
       document.body.appendChild(el);
   }
   el.style.cssText = "bacground-color:" + color;
}
----
=== Handling infinite scrolling

The `recurs` boolean (<<JSON manifest>>) is used to specify whether the script's entrypoint function should be called again when
the thread (`'[data-controller="subject-list"]\'`) or post content area (`'#comments'`) has DOM changes. This allows your mod to be applied again in the event of post replies, new threads being loaded in,
et cetera.

Simply set this value in the manifest and the script will be called automatically and applied to the new content.
There is no need to include additional onload event listeners to the script itself or watch for page events, as they are handled
at the top level by KES.

=== Submitting a PR

1. Clone the repo and prepare a patch against the `testing` branch.

2. If you are submitting a userscript, limit PRs to one per atomic script. If a collection of functions in the script are semantically related to each other, you may
choose to group them into one script, but they must be given unique objects, entrypoints, and namespaces within `manifest.json` (one feature per add-on). Generally speaking, different features should be limited to atomic scripts.

3. Scripts should not wantonly change the appearance and style of the page in the way a CSS theme would.
Limit features to small functionality changes that leverage the advantages of JS over CSS.
KES works best in the aggregate, when its add-ons synergize with each other.

4. For testing purposes, you can define remote resources in the `@require` fields of the `kes.user.js` headers when debugging, but the PR itself must not include any
modifications to this file or to the `VERSION` file. Only submit a modified `manifest.json` and add your script to the `/mods` directory.

5. Ensure that the `entrypoint` and `namespace` (if applicable) defined in `manifest.json` are globally unique.

6. If your script has external dependencies (`@require`) that are not included in KES, please request these to be added when making the PR. Note that jQuery is provided by default and can be used to reduce the verbosity of your script.

[NOTE]
If you are submitting a PR changing an internal feature of KES itself, feel free to include changes to other files than the above.

=== Precautions and best practices

- Prefer private functions and local variables to reduce the possibility of collisions

Bear in mind that KES ingests all of the script functions together into its scope, so unique identifiers are important.
While scripts are integration tested before deployment, you can make the testing process easier by using unique names and limiting the available
scope.

- No need to handle extra event listeners

Unless you are creating a special button or widget, there is no need to actively watch the page for changes (e.g. `onload`), as KES
handles this for you and will apply your changes accordingly in the event of infinite scrolling, reload events, etc.

- Aim for minimal, concise features that do one simple thing well

Most scripts can be ported over as-is with little or no changes, but remember that KES is designed to take the complexity of setup out of the
equation, allowing many small mods to be incorporated and synergize with each other. It is enough to create an entrypoint function that triggers some
changes, request the desired UI via the JSON manifest, and the rest should work out of the box. Therefore, think of scripts as atomic features rather than
complex workflows; scripts that make highly opinionated changes or themselves create complex menus may be difficult to adapt.

==== Conventions
- Prefer 4-space indentation
- Prefer https://www.conventionalcommits.org/en/v1.0.0/[conventional commits]
- Linting with ESLint is encouraged but not required

