:nofooter:
:toc: left
:stylesheet: custom.css
:icons: font

= kbin Enhancement Suite (KES)
Add-on manager for kbin enhancement scripts | Last updated: {d}

Click https://aclist.github.io/kes/kes_dark.html[here] for dark mode

== Description

KES aims to provide an integrated, paginated menu for managing settings provided by third-party userscripts
that change or add functionality to the frontend of kBin instances.

It also provides a simple, human-readable format for script authors to integrate new options with minimal overhead.

== Prerequisites

KES is itself a userscript that bundles other scripts. As such, it requires any of the below 
browser extensions in the *monkey family:

- TamperMonkey
- GreaseMonkey
- ViolentMonkey

Versions for Firefox- and Chromium-based browsers can be found on your respective add-on/extensions page.

== Installation

Navigate to https://github.com/aclist/kbin-megamod/raw/main/megamod.user.js[the install script] and
follow your browser extension's onscreen prompts to install it. Subsequent updates should be handled
seamlessly, and KES will notify you if there is a new version available.

== Usage
TODO: remarks on ctrl-shift-l and escape buttons, docking, wrench icon, etc.

To open the KES settings menu, press `Ctrl-Shift-L` or click the wrench icon in the top right corner of the page. Pressing `Esc`, or clicking on the close button or anywhere outside of the menu will close it.

The menu is divided into pages, and each page contains a list of modifications. You can switch between pages by clicking on the page name in the list on the left side of the menu (or the top if on mobile). 

Clicking the name of a modification will open an information panel with a description of the modification, a toggle to enable/disable it. If the modification has any additional settings, they can be configured here.

On devices where the menu doesn't take up the whole screen, it can be docked to the bottom of the screen by clicking the arrow icon in the top right corner of the menu. Clicking the arrow again will undock the menu.

== Developers

If you wish to submit your scripts for integration into KES, a standardized framework is available that
makes adaptation and PR submission easy:

The metadata related to a script is defined a priori in the file `manifest.json`. KES automatically populates
its pages and assigns your add-on to the category requested, filling its contents with the fields and values you set.

1. Set up an entrypoint function in the script which enables/disables it
2. Receive a boolean toggle argument from KES passed to the above function indicating
whether the user has toggled the script on or off
3. If the script defines custom input fields, use the `getModSettings()` function exposed by KES
with your script's namespace as the argument
4. Parse the resulting settings object for your desired keys and use these settings in the business
logic of your script

Detailed explanations follow.

=== JSON

`manifest.json` consists of an array of objects that each represent an add-on, that is, an atomic
feature provided by a function in a third-party userscript.
Add-ons are variously referred to as "features," "add-ons," and "mods" within this document.
Add-ons must be given a globally unique entrypoint function name and, if using custom input fields,
a globally unique namespace.

If the add-on requires custom input fields like select, radio, or
other https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input[input types], they can be added under
the `fields` array, one custom field per object.

The namespace is used to store settings under a localStorage object, which is used to share
settings between KES and third-party add-ons, or between third-party add-ons.


.localStorage
----
Storage {
    "kes-settings":
        '{
            "addMail":true,
            "initMags":true,
            "magInstanceEntry":true,
            "hideDownvotes":true,
            "hideUpvotes":true,
            "updateTime":true,
            "changeLogo":false,
            "dock":"up",
            "checksInit":true
        }',
    codehighlights: '{"style":"gruvbox"}',
    languagefilter: '{"filter":"English"}',
    mail: '{"type":"Text","text":"PM","state":"on"}',
    timestamp: '{"offset":"Local time","state":"on"}',
    length: 6
}
----

In the above example, KES has saved the state of eight add-ons, seven of which are enabled by the user.
In addition, it has stored the position of the KES window to `up`. (This is not controlled by third party add-ons.)
Finally, the add-ons `codehighlights`, `languagefilter`, `mail`, and `timestamp` have respectively set 
their own settings in custom namespaces.

KES handles toggling of add-ons and passes their state to the recipient script. The recipient script 
does not need to poll this state, receiving it as an incoming boolean argument.
The only responsibility of the recipient script is to parse its own namespace under localStorage and 
retrieve custom settings. To facilitate this, KES provides the `getModSettings()` function.

.manifest.json
----
  {
    "name": "Add mail",
    "author": "shazbot",
    "version": "0.1.0",
    "label": "Add mail icon",
    "desc": "Add mail link to usernames if on kbin.social",
    "login": false,
    "recurs": true,
    "link": "aclist.github.io",
    "link_label" "My link"
    "class": "addMail",
    "entrypoint": "addMail",
    "namespace": "mail",
    "fields": [ <1>
      {
        "type": "radio",
        "initial": "Text",
        "key": "type",
        "label": "Label type",
	"values": [
		"Text",
		"Icon"
	]
      },
      { <2>
        "type": "text",
        "initial": "PM",
        "key": "text",
        "label": "Link label"
      }
    ],
    "page": "general" <2>
  }
----
<1> See <<Table 2. The fields array>> below. In the above example, the descriptive text 'Label type' will be printed on one line, followed by a line break, then two radio buttons respectively labeled 'Text' and 'Icon', in that order,
will be printed, with the 'Text' radio button initially selected.
<2> The value 'Text' will be saved under the `mail.type` key and updated if the user changes the radio button. This is followed by a descriptive label reading 'Text label', a line break,
and then a textarea initially set to the string 'PM', with this value stored under the `mail.text` key.
<3> The contents of the metadata and custom fields will be added to the 'General' page of the sidebar under the feature 'Add mail icon'.

.basic metadata
[%autowidth]
|===
|Key|Optional?|Type|Value

|name||string|An internal, "official" name of the add-on, possibly more verbose than the user-facing string
|author||string|The author of the add-on. This is user-facing and links back to the named profile on kBin.
TODO: does this work across instances?
|version||string|An internal version number
|label||string|A short, descriptive name of the feature, used when printing it in the list of options. This
functions as the "name" of the feature seen by users.
|desc||string|A human-readable description of what the feature does
|login||boolean|Whether the option requires being logged into the site to function/display correctly
|recurs||boolean|If the feature should recur and apply to new elements in the tree in the event of DOM changes
to the `'#content'` area, such as new posts or threads when lazy load (infinite scrolling) is enabled
|entrypoint||string|A globally unique function entrypoint in the recipient script used to toggle the feature
on or off.
|namespace|yes|string|A globally unique namespace used if the add-on exposes custom input fields (see below)
This namespace is used when parsing localStorage
|link|yes|string|A link to external content, such as a web site or help file
|link_label|yes|string|A human-readable label for the link above
|fields|yes|string|An array of objects containing custom input fields
|===

=== Adding custom input fields

.The fields array
[%autowidth]
|===
|Key|Optional?|Type|Value

|type||string|The input field type
|initial||string (if checkbox, bool)|The initial value
|key||string|a unique key for this atomic setting, stored under the object namespace defined above
|label|yes|string|a descriptive label of what the setting does, printed above the input field on a newline
|values|required if `type` is select or radio|array of strings|if the type is `select` or `radio`, an array of human-readable labels, which also function as values, used to populate each option
|checkbox_label|required if `type` is checkbox|string
|===

=== Script calling logic
TODO: example of how toggle might work
----
function myEntryPoint(toggle) {
    if (toggle)
	//toggle logic
    } else {
	//untoggle
}
----
[NOTE]
Must check if element already exists and act accordingly, esp. if recurring

=== Retrieving custom settings

inline example of querying settings with getModSettings and parsing settings

----
const ns = mymod;
const settings = getModSettings(myns);
const color = settings["color"];
const mydiv = document.querySelector("mydiv");
mydiv.style.cssText = 'background-color:' + color;
----

=== Handling infinite scrolling

`recurs` boolean

simply set it in the manifest

TODO: inline example

=== Submitting a PR

1. Clone the repo and prepare a patch against the `testing` branch.

2. If you are submitting a userscript, limit PRs to one per atomic script. If a collection of functions in the script are semantically related to each other, you may
choose to group them into one script, but they must be given unique objects, entrypoints, and namespaces within `manifest.json` (one feature per add-on). Generally speaking, different features should be limited to atomic scripts.

3. Scripts should not wantonly change the appearance and style of the page in the way a CSS theme would.
Limit features to small functionality changes that leverage the advantages of JS over CSS.
KES works best in the aggregate, when its add-ons synergize with each other.

4. For testing purposes, you can define remote resources in the `@require` fields of the `kes.user.js` headers when debugging, but the PR itself must not include any
modifications to this file or to the `VERSION` file. Only submit a modified `manifest.json` and add your script to the `/mods` directory.

5. Ensure that the `entrypoint` and `namespace` (if applicable) defined in `manifest.json` are globally unique.

[NOTE]
If you are submitting a PR changing an internal feature of KES itself, feel free to include changes to other files than the above.

=== Conventions

- Prefer 4-space indentation
- Prefer https://www.conventionalcommits.org/en/v1.0.0/[conventional commits]
- Anything else? E.g. linting with ES

